# --- Build stage ---
FROM node:20-alpine AS builder
WORKDIR /app
 
# Install deps
COPY package*.json ./

RUN npm ci
 
 
# Copy source code
COPY . .
 
 
 
ARG NEXT_PUBLIC_API_URL_USERS
ARG NEXT_PUBLIC_API_URL_PRODUCTS
ARG NEXT_PUBLIC_API_URL_CART
ARG NEXT_PUBLIC_API_URL_ORDER
ARG NEXT_PUBLIC_API_URL_HELPDESK
ARG NEXT_PUBLIC_API_URL_CMS
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_GOOGLE_MAPS_KEY
ARG NEXT_PUBLIC_API_URL_PAYMENT
ARG NEXT_PUBLIC_API_URL_PAYMENTS
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_GEOLOCATION_API_KEY
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID

ENV NEXT_PUBLIC_API_URL_USERS=$NEXT_PUBLIC_API_URL_USERS
ENV NEXT_PUBLIC_API_URL_PRODUCTS=$NEXT_PUBLIC_API_URL_PRODUCTS
ENV NEXT_PUBLIC_API_URL_CART=$NEXT_PUBLIC_API_URL_CART
ENV NEXT_PUBLIC_API_URL_ORDER=$NEXT_PUBLIC_API_URL_ORDER
ENV NEXT_PUBLIC_API_URL_HELPDESK=$NEXT_PUBLIC_API_URL_HELPDESK
ENV NEXT_PUBLIC_API_URL_CMS=$NEXT_PUBLIC_API_URL_CMS
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_KEY
ENV NEXT_PUBLIC_API_URL_PAYMENT=$NEXT_PUBLIC_API_URL_PAYMENT
ENV NEXT_PUBLIC_API_URL_PAYMENTS=$NEXT_PUBLIC_API_URL_PAYMENTS
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_GEOLOCATION_API_KEY=$NEXT_GEOLOCATION_API_KEY
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID

# Build Next.js (standalone output)
RUN npm run build
 
# --- Runtime stage ---
FROM node:20-alpine AS runner
WORKDIR /app
 
ENV NODE_ENV=production
# Intentionally 3001, not the 3000 in package.json's `start` script — that
# script isn't used here. The standalone server.js reads PORT directly, so
# this is the actual port the container listens on; keep it in sync with
# whatever the deployment target (e.g. Cloud Run) is configured to hit.
ENV PORT=3001
 
# Copy standalone server generated by Next.js
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# next/image's optimizer needs sharp's native binary at runtime; standalone
# output tracing doesn't reliably pick it up, so copy it explicitly from the
# builder (same base image/arch, so the compiled binary matches).
COPY --from=builder /app/node_modules/sharp ./node_modules/sharp
COPY --from=builder /app/node_modules/@img ./node_modules/@img
 
EXPOSE 3001
 
CMD ["node", "server.js"]
