export const API_ENDPOINTS = {
  AUTH: {
    BASE_URL: `${process.env.NEXT_PUBLIC_API_URL_USERS}/api/v1/users`,
    BASE_URL_CLIENT: "/api/v1/user",
    LOGIN: "login",
    SIGNUP: "signup",
    LOGOUT: "logout",
    FORGOT_PASSWORD: "forgot-password", // NOSONAR
    RESET_PASSWORD: "reset-password", // NOSONAR
    USER_DETAILS: "profile",
    VERIFY_EMAIL: (token: string) => `verify-email/${token}`,
    CHANGE_PASSWORD: "change-password", // NOSONAR
    ADDRESS: "address",
    PERSONAL_DATA: "profile",
    GOOGLE_LOGIN: "google-login",
  },
  PRODUCTS: {
    BASE_URL: "/api/v1/product",
    PRODUCTS_API_BASE_URL:
      process.env.NEXT_PUBLIC_API_URL_PRODUCTS ||
      "https://api.shopperbeats.com.au/products",
    PRODUCT_BASE_URL: `${process.env.NEXT_PUBLIC_API_URL_PRODUCTS}/api/v1/product`,
    PRODUCT_BASE_URL_CLIENT: `/api/v1/product`,
    ALL: "/api/products",
    LIST_PRODUCTS: "list-products",
    BY_ID: (id: string) => `/api/products/${id}`,
    POPULAR: "popular-products",
    RECENTLY_VIEWED: "/recently-viewed",
    HOMEPAGE_SECTIONS: "home-sections",
    HERO_BANNER: "hero_banner",
    TOP_CATEGORIES: "top-categories",
    BANNER_ONE: "banner_one",
    BANNER_TWO: "banner_two",
    CUSTOMER_REVIEWS: "customer_reviews",
    TRENDING_DEALS: "trending-deals",
    TOP_RATED: "top-rated",
    BRANDS_LIST: "/api/v1/brand/list-brands",
    TRENDING_PRODUCTS: "trending-products",
    GET_PRODUCT: "get-product",
    RECOMMENDATION: "recommendations",
    HOMEPAGE_SECTION_BY_ID: (section: string) => `/api/v1/homepage/${section}`,
    PERSONALIZED: "/api/v1/product-user/personalized",
    BESTSELLERS: "/best-sellers",
    HIGHLIGHTS: "/api/v1/product-highlights",
    LIST_PROMOTIONAL_PRODUCTS: "list-promotional-products",
    UPLOAD_ANY_IMAGE: "upload-any-image",
  },
  CART: {
    BASE_URL: `${process.env.NEXT_PUBLIC_API_URL_CART}/api/v1/cart`,
    BASE_URL_CLIENT: "/api/v1/cart",
    GET: "/get-cart",
    ADD: "/add-to-cart",
    UPDATE: "/update-cart",
    REMOVE: "/remove-from-cart",
    CHECK_DELIVERY: "/check-delivery",
    PROMO_BASE_URL: `${process.env.NEXT_PUBLIC_API_URL_CART}/api/v1/coupon`,
    CLEAR: "clear-cart",
    VALIDATE: `${process.env.NEXT_PUBLIC_API_URL_CART}/api/v1/coupon-tracker/validate`,
  },
  WISHLIST: {
    BASE_URL: `${process.env.NEXT_PUBLIC_API_URL_CART}/api/v1/wishlist`,
    BASE_URL_CLIENT: "/api/v1/wishlist",
    CREATE: "/create-wishlist",
    GET: "/get-wishlist",
    REMOVE: "/delete-wishlist",
  },
  CATEGORIES: {
    LIST: "/api/v1/category/list-category",
    BY_SLUG: (slug: string) => `/api/v1/category/get-category-by-slug/${slug}`,
  },
  ORDER: {
    BASE_URL: `/api/v1/order`,
    CREATE: "/orders/create-orders",
    LIST: "/orders/list-orders",
    DETAIL: "/orders/get-order",
    CANCEL_SHIPPSTATION_ORDER: "/shipstation/delete-order",
    CANCEL_ITEM: (id: string | number) => `/orders/cancel-order-item/${id}`,
    CANCEL_ORDER: (order_id: string) => `/orders/cancel-order/${order_id}`,
    SHIPPING_CHARGE: "/shipping-rules/calculate-shipping",
    RETURN_OPTIONS: "/return-reasons/active",
    RETURN: (order_id: string) => `/orders/return-order/${order_id}`,
    RETURN_ITEM: (item_id: string | number) => `/orders/return-order-item/${item_id}`,
    REPLACE: (order_id: string) => `/orders/replace-order/${order_id}`,
    REPLACE_ITEM: (item_id: string | number) => `/orders/replace-order-item/${item_id}`,
    ADD_REVIEW: "/orders/add-review",
    RETRY_PAYMENT: (order_id: string) => `/orders/retry-payment/${order_id}`,
    GET_INVOICE: (order_id: string) => `/api/v1/orders/get-invoice/${order_id}`,
  },
  HELPDESK: {
    BASE_URL: `/api/v1/helpdesk`,
    CONTACT_US: "/contact-us",
  },
  CMS: {
    BASE_URL: `${process.env.NEXT_PUBLIC_API_URL_CMS}/cms/api`,
    BY_SLUG: (slug: string) => `/${slug}`,
  },
  MARKETING: {
    BASE_URL: `${process.env.NEXT_PUBLIC_API_URL_USERS}/api/v1/marketing`,
    MAILING_LIST: "/mailing-list",
  },
  PAYMENT: {
    BASE_URL: "/api/v1/payment",
    INITIATE: "/initiate",
    CAPTURE: "/paypal/capture",
  },
  MENU: {
    BASE_URL: `${process.env.NEXT_PUBLIC_API_URL_USERS}/api/v1/menu`,
    BY_SLUG: (slug: string) => `/api/v1/menu/${slug}`,
  },
  SOCIAL_MEDIA: {
    GET_LINKS: `/api/v1/social-media/links`,
  },
  PROMOTIONS: {
    BASE_URL: "/api/v1/promotions",
    LIST: "list-promotions",
  },
  FAQ: {
    BASE_URL: `/api/v1/faqs`,
  },
};
